# Generated by Django 3.0.6 on 2020-06-10 04:47

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=martor.models.MartorField(),
        ),
    ]
