# Generated by Django 3.0.6 on 2020-06-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0002_auto_20200610_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('link', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
