# Generated by Django 3.0.6 on 2020-06-23 05:47

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=martor.models.MartorField(),
        ),
    ]
