# Generated by Django 3.0.6 on 2020-06-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0004_auto_20200623_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.IntegerField(default=0),
        ),
    ]
