# Generated by Django 3.0.6 on 2020-06-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0005_post_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='', max_length=280),
            preserve_default=False,
        ),
    ]
